### ISSUE TITLE
Client for Snell

### ISSUE THREAD

**Issue by SanujaNS** [SebErstellen/snell#3]
Hello @SebErstellen ,

I'm searching for a Snell clients for Linux. As you know, Snell is a closed-source protocol by Surge so there isn't much of a choice. I'm aware that Clash works with Snell up to version 3.0.1, but I'm wondering if there are any other clients available that supports the latest version of Snell (v4.0.1).
Do you have any experience with Snell clients for Linux or do you know of any Snell clients for Linux that support v4.0.1?
I'd be grateful if you could provide me information you think would be helpful.

Thank you.

**Comment by sebersta** [comment]
I’m also curious to know, but as of now, since no one has reverse-engineered an open port for Shell v4, it appears that Surge is the only client that supports Shell v4.
